import { slugify, monthly } from "./format";

export type Condition = "Brand New" | "Excellent" | "Refurbished";
export type StockStatus = "In Stock" | "Low Stock" | "Sold Out" | "Coming Soon";

export interface Product {
  id: string;
  slug: string;
  name: string;
  year: number;
  price: number;
  oldPrice?: number | undefined;
  storage: string[];
  colours: string[];
  batteryHealth: string;
  condition: Condition;
  stock: StockStatus;
  stockQty: number;
  rating: number;
  reviews: number;
  badges: string[];
  tradeInValue: number;
  specs: {
    display: string;
    displayType: string;
    chipset: string;
    ram: string;
    camera: string;
    frontCamera: string;
    video: string;
    battery: string;
    faceId: string;
    dynamicIsland: string;
    magsafe: string;
    port: string;
    water: string;
    weight: string;
  };
}

type Raw = [
  name: string,
  year: number,
  price: number,
  storage: string[],
  colours: string[],
  battery: string,
  condition: Condition,
  stock: StockStatus,
  qty: number,
  rating: number,
  reviews: number,
  badges: string[],
  specs: Product["specs"],
];

const s = (
  display: string,
  displayType: string,
  chipset: string,
  ram: string,
  camera: string,
  frontCamera: string,
  video: string,
  battery: string,
  faceId: string,
  dynamicIsland: string,
  magsafe: string,
  port: string,
  water: string,
  weight: string,
): Product["specs"] => ({
  display,
  displayType,
  chipset,
  ram,
  camera,
  frontCamera,
  video,
  battery,
  faceId,
  dynamicIsland,
  magsafe,
  port,
  water,
  weight,
});

const raw: Raw[] = [
  [
    "iPhone XR",
    2018,
    4500,
    ["64GB", "128GB", "256GB"],
    ["Black", "White", "Blue", "Coral", "Red"],
    "86%",
    "Refurbished",
    "In Stock",
    12,
    4.4,
    168,
    [],
    s(
      '6.1"',
      "Liquid Retina LCD",
      "A12 Bionic",
      "3GB",
      "12MP Wide",
      "7MP TrueDepth",
      "4K @ 60fps",
      "Up to 16 hrs",
      "Yes",
      "No",
      "No",
      "Lightning",
      "IP67",
      "194g",
    ),
  ],
  [
    "iPhone XS",
    2018,
    5000,
    ["64GB", "256GB"],
    ["Space Gray", "Silver", "Gold"],
    "85%",
    "Refurbished",
    "Low Stock",
    3,
    4.3,
    121,
    [],
    s(
      '5.8"',
      "Super Retina OLED",
      "A12 Bionic",
      "4GB",
      "12MP Dual",
      "7MP TrueDepth",
      "4K @ 60fps",
      "Up to 14 hrs",
      "Yes",
      "No",
      "No",
      "Lightning",
      "IP68",
      "177g",
    ),
  ],
  [
    "iPhone 11",
    2019,
    5500,
    ["64GB", "128GB", "256GB"],
    ["Black", "White", "Purple", "Green", "Red"],
    "88%",
    "Excellent",
    "In Stock",
    18,
    4.6,
    302,
    ["Best Seller"],
    s(
      '6.1"',
      "Liquid Retina LCD",
      "A13 Bionic",
      "4GB",
      "12MP Dual (Ultra Wide)",
      "12MP TrueDepth",
      "4K @ 60fps",
      "Up to 17 hrs",
      "Yes",
      "No",
      "No",
      "Lightning",
      "IP68",
      "194g",
    ),
  ],
  [
    "iPhone 11 Pro",
    2019,
    6500,
    ["64GB", "256GB", "512GB"],
    ["Space Gray", "Silver", "Gold", "Midnight Green"],
    "87%",
    "Excellent",
    "In Stock",
    9,
    4.6,
    214,
    [],
    s(
      '5.8"',
      "Super Retina XDR OLED",
      "A13 Bionic",
      "4GB",
      "12MP Triple",
      "12MP TrueDepth",
      "4K @ 60fps",
      "Up to 18 hrs",
      "Yes",
      "No",
      "No",
      "Lightning",
      "IP68",
      "188g",
    ),
  ],
  [
    "iPhone 12",
    2020,
    6800,
    ["64GB", "128GB", "256GB"],
    ["Black", "White", "Blue", "Green", "Purple", "Red"],
    "89%",
    "Excellent",
    "In Stock",
    22,
    4.7,
    388,
    ["Customer Favourite"],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A14 Bionic",
      "4GB",
      "12MP Dual",
      "12MP TrueDepth",
      "4K Dolby Vision @ 60fps",
      "Up to 17 hrs",
      "Yes",
      "No",
      "Yes",
      "Lightning",
      "IP68",
      "164g",
    ),
  ],
  [
    "iPhone 12 Pro",
    2020,
    8200,
    ["128GB", "256GB", "512GB"],
    ["Graphite", "Silver", "Gold", "Pacific Blue"],
    "88%",
    "Excellent",
    "Low Stock",
    4,
    4.7,
    265,
    [],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A14 Bionic",
      "6GB",
      "12MP Triple + LiDAR",
      "12MP TrueDepth",
      "4K Dolby Vision @ 60fps",
      "Up to 17 hrs",
      "Yes",
      "No",
      "Yes",
      "Lightning",
      "IP68",
      "189g",
    ),
  ],
  [
    "iPhone 13",
    2021,
    8500,
    ["128GB", "256GB", "512GB"],
    ["Midnight", "Starlight", "Blue", "Pink", "Green", "Red"],
    "91%",
    "Excellent",
    "In Stock",
    26,
    4.8,
    512,
    ["Best Seller", "Trending"],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A15 Bionic",
      "4GB",
      "12MP Dual",
      "12MP TrueDepth",
      "4K Cinematic @ 30fps",
      "Up to 19 hrs",
      "Yes",
      "No",
      "Yes",
      "Lightning",
      "IP68",
      "174g",
    ),
  ],
  [
    "iPhone 13 Pro",
    2021,
    10500,
    ["128GB", "256GB", "512GB", "1TB"],
    ["Graphite", "Silver", "Gold", "Sierra Blue", "Alpine Green"],
    "90%",
    "Excellent",
    "In Stock",
    11,
    4.8,
    341,
    [],
    s(
      '6.1"',
      "Super Retina XDR ProMotion",
      "A15 Bionic",
      "6GB",
      "12MP Triple + LiDAR",
      "12MP TrueDepth",
      "ProRes 4K @ 30fps",
      "Up to 22 hrs",
      "Yes",
      "No",
      "Yes",
      "Lightning",
      "IP68",
      "204g",
    ),
  ],
  [
    "iPhone 14",
    2022,
    9000,
    ["128GB", "256GB", "512GB"],
    ["Midnight", "Starlight", "Blue", "Purple", "Yellow", "Red"],
    "93%",
    "Excellent",
    "In Stock",
    20,
    4.7,
    289,
    ["Most Popular"],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A15 Bionic",
      "6GB",
      "12MP Dual",
      "12MP TrueDepth AF",
      "4K Action Mode",
      "Up to 20 hrs",
      "Yes",
      "No",
      "Yes",
      "Lightning",
      "IP68",
      "172g",
    ),
  ],
  [
    "iPhone 14 Pro",
    2022,
    12400,
    ["128GB", "256GB", "512GB", "1TB"],
    ["Space Black", "Silver", "Gold", "Deep Purple"],
    "92%",
    "Excellent",
    "In Stock",
    8,
    4.9,
    402,
    ["Trending"],
    s(
      '6.1"',
      "Super Retina XDR ProMotion",
      "A16 Bionic",
      "6GB",
      "48MP Triple + LiDAR",
      "12MP TrueDepth AF",
      "ProRes 4K @ 60fps",
      "Up to 23 hrs",
      "Yes",
      "Yes",
      "Yes",
      "Lightning",
      "IP68",
      "206g",
    ),
  ],
  [
    "iPhone 15",
    2023,
    11800,
    ["128GB", "256GB", "512GB"],
    ["Black", "Blue", "Green", "Yellow", "Pink"],
    "96%",
    "Brand New",
    "In Stock",
    30,
    4.8,
    356,
    ["Best Seller"],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A16 Bionic",
      "6GB",
      "48MP Dual",
      "12MP TrueDepth AF",
      "4K Dolby Vision @ 60fps",
      "Up to 20 hrs",
      "Yes",
      "Yes",
      "Yes",
      "USB-C",
      "IP68",
      "171g",
    ),
  ],
  [
    "iPhone 15 Pro",
    2023,
    14300,
    ["128GB", "256GB", "512GB", "1TB"],
    ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
    "95%",
    "Brand New",
    "In Stock",
    14,
    4.9,
    471,
    ["Customer Favourite"],
    s(
      '6.1"',
      "Super Retina XDR ProMotion",
      "A17 Pro",
      "8GB",
      "48MP Triple + LiDAR",
      "12MP TrueDepth AF",
      "ProRes 4K @ 60fps (log)",
      "Up to 23 hrs",
      "Yes",
      "Yes",
      "Yes",
      "USB-C",
      "IP68",
      "187g",
    ),
  ],
  [
    "iPhone 16",
    2024,
    14300,
    ["128GB", "256GB", "512GB"],
    ["Black", "White", "Pink", "Teal", "Ultramarine"],
    "100%",
    "Brand New",
    "In Stock",
    25,
    4.9,
    288,
    ["Best Seller"],
    s(
      '6.1"',
      "Super Retina XDR OLED",
      "A18",
      "8GB",
      "48MP Fusion Dual",
      "12MP TrueDepth AF",
      "4K Dolby Vision @ 60fps",
      "Up to 22 hrs",
      "Yes",
      "Yes",
      "Yes",
      "USB-C",
      "IP68",
      "170g",
    ),
  ],
  [
    "iPhone 16 Pro",
    2024,
    18000,
    ["128GB", "256GB", "512GB", "1TB"],
    ["Black Titanium", "Natural Titanium", "White Titanium", "Desert Titanium"],
    "100%",
    "Brand New",
    "In Stock",
    10,
    4.9,
    331,
    ["Most Popular"],
    s(
      '6.3"',
      "Super Retina XDR ProMotion",
      "A18 Pro",
      "8GB",
      "48MP Triple + LiDAR",
      "12MP TrueDepth AF",
      "4K120 ProRes / log 2",
      "Up to 27 hrs",
      "Yes",
      "Yes",
      "Yes",
      "USB-C",
      "IP68",
      "199g",
    ),
  ],
];

export const products: Product[] = raw.map(
  (
    [
      name,
      year,
      price,
      storage,
      colours,
      batteryHealth,
      condition,
      stock,
      stockQty,
      rating,
      reviews,
      badges,
      specs,
    ],
    i,
  ) => ({
    id: String(i + 1),
    slug: slugify(name),
    name,
    year,
    price,
    oldPrice: i % 3 === 0 ? Math.round(price * 1.14) : undefined,
    storage,
    colours,
    batteryHealth,
    condition,
    stock,
    stockQty,
    rating,
    reviews,
    badges,
    tradeInValue: Math.round(price * 0.42),
    specs,
  }),
);

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);

export const monthlyFor = (price: number) => monthly(price, 24);

export const newArrivals = products.filter((p) => p.year >= 2025);
export const bestSellers = products.filter((p) =>
  p.badges.some((b) =>
    ["Best Seller", "Most Popular", "Customer Favourite", "Trending"].includes(b),
  ),
);

export const conditions: Condition[] = ["Brand New", "Excellent", "Refurbished"];
export const allStorage = ["64GB", "128GB", "256GB", "512GB", "1TB", "2TB"];
export const allColours = Array.from(new Set(products.flatMap((p) => p.colours))).sort();

export const testimonials = [
  {
    name: "Thandi M.",
    city: "Durban",
    rating: 5,
    text: "Ordered an iPhone 15 Pro on Monday, delivered Wednesday. Sealed, genuine, and the price beat every store I checked.",
  },
  {
    name: "Sipho N.",
    city: "Johannesburg",
    rating: 5,
    text: "Traded in my iPhone 12 and paid the difference on my Visa card. The whole process took under 15 minutes.",
  },
  {
    name: "Lerato K.",
    city: "Pretoria",
    rating: 5,
    text: "Battery health was exactly as advertised at 91%. Honest sellers are rare — Mgwaba iStore is the real deal.",
  },
  {
    name: "Ayanda P.",
    city: "Cape Town",
    rating: 4,
    text: "Great communication on WhatsApp throughout. They even followed up after delivery to check everything worked.",
  },
  {
    name: "Riaan v.d. Merwe",
    city: "Bloemfontein",
    rating: 5,
    text: "Bought two iPhone 14s for the family on the 12-month plan. Zero hassle, warranty documents included.",
  },
  {
    name: "Nokuthula D.",
    city: "Polokwane",
    rating: 5,
    text: "The refurbished iPhone 11 looks brand new. Free delivery and a case included — I'll be back.",
  },
];

export const faqs = [
  {
    q: "Are the phones original?",
    a: "Every device we sell is a genuine Apple iPhone. We verify IMEI and serial numbers with Apple's activation database before listing, and you receive the verification report with your order.",
  },
  {
    q: "Do you offer warranties?",
    a: "Yes. Brand new devices carry the full Apple limited warranty. Excellent and Refurbished devices include a 6-month Mgwaba iStore hardware warranty, with an optional 12-month extension.",
  },
  {
    q: "How long is delivery?",
    a: "Main centres receive orders within 1–2 business days. Outlying areas take 2–4 business days. Every order ships insured with a live tracking number.",
  },
  {
    q: "Do you accept trade-ins?",
    a: "We do. Use our Trade-In Calculator for an instant estimate, then request a quote. Once your device is inspected the value is applied directly to your new iPhone.",
  },
  {
    q: "What payment methods do you accept?",
    a: "Visa and Mastercard (debit and credit), bank transfer / EFT with proof of payment, and Buy Now Pay Later instalment plans from 3 to 24 months.",
  },
  {
    q: "Is my card payment secure?",
    a: "Yes. Checkout runs over SSL with PCI DSS compliant processing and 3D Secure authentication. We never store raw card numbers on our servers.",
  },
];

export const whatsInTheBox = [
  { label: "iPhone", note: "Your selected model, colour and storage" },
  { label: "USB-C Charging Cable", note: "Braided cable (Lightning on older models)" },
  { label: "SIM Eject Tool", note: "Included where applicable" },
  { label: "Documentation", note: "Warranty card and quick start guide" },
  { label: "Apple Stickers", note: "Included on sealed retail units" },
];
